site_name: EasyBench
site_url: https://easybench.readthedocs.io/

repo_name: smurak/easybench
repo_url: https://github.com/smurak/easybench

theme:
  name: material
  language: en

plugins:
  - search
  - mkdocstrings

nav:
  - Home: index.md
  - Quick Start: quickstart.md
  - Usage:
    - Decorator-based Benchmarks: usage/decorator-based.md
    - Class-based Benchmarks: usage/class-based.md
    - Command Line Interface: usage/command-line.md
    - Jupyter Notebook Magic Command: usage/notebook-magic.md
  - Advanced Usage:
    - Customizing Output: advanced/customize-output.md
    - Creating Custom Reporters and Formatters: advanced/custom-reporters.md
    - Visualization: advanced/visualization.md
  - API Reference:
    - CLI: reference/cli.md
    - Core: reference/core.md
    - Decorator: reference/decorator.md
    - Reporters: reference/reporters.md
    - Visualization: reference/visualization.md
    - Utils: reference/utils.md

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences

extra:
  alternate:
    - name: English
      link: /
      lang: en
    - name: Japanese
      link: /ja/
      lang: ja

exclude_docs: |
  ja/
